services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: weather_notifier_api
    build:
      context: ./api
    environment:
      - DB_URL=postgresql://postgres:postgres@postgres:5432/postgres
    ports:
      - "8001:8000"
    healthcheck:
      test:
    depends_on:
      postgres:
        condition: service_healthy
  notifier:
    image: weather_notifier
    build:
      context: ./notifier
    environment:
      - API_KEY=${API_KEY}
      - SUBSCRIPTION_API_URL=http://app:8000
      - SMTP_HOST=email:1025
    depends_on:
      - app
  email:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
